TELEGRAM_BOT_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN"
OPENAI_API_KEY = "YOUR_OPENAI_API_KEY"
LANGUAGE_CODE = "en-US"
VOICE_NAME = "en-US-Wavenet-D"
WHISPER_MODEL = "whisper-1"
GPT_MODEL = "gpt-4"
MAX_GPT_TOKENS = 1000
